### ISSUE TITLE
Implement GPU endpoints with provider discovery

### ISSUE THREAD

**Issue by baktun14** [akash-network/console#106]
The endpoints:
- List all the gpus network wide
- List the gpus by provider
- List the providers by gpu vendor/model

**Comment by troian** [comment]
the api response should be as following

```json
{
  "gpus" : {
    "total": {
      "allocated": "1",
      "allocatable": "1",
    },
    "details": {
      "nvidia": [
        {
          "model": "a100",
          "ram": "40Gi",
          "interface": "PCIe|SXM4"
          "allocatable": 1,
          "allocated": 1
        }
      ]
    }
  }
}
```

- default query should return totals and details for all of the providers on the network
- query param `provider` filters results per provider
- query param `vendor` filters results per vendor
- query param `model` filters results per model
- query param `memory_size` filters results results with memory size

all query params above can be combined

**Comment by Redm4x** [comment]
PR #109 adds a `/internal/gpu` endpoint using this spec. Currently waiting on more gpu providers to upgrade before merging to make sure the returned data is accurate. The `provider` query param will accept either a provider address or a host uri.

This endpoint is relying on the assumption that all GPUs within a node are the same. If that ever changes, the provider's status endpoint should be changed accordingly for this endpoint to continue reporting accurate information.
