### ISSUE TITLE
Feature: Implement new api endpoint for total lease active time

### ISSUE THREAD

**Issue by baktun14** [akash-network/console#119]
- The api endpoint receives an address and/or a dseq, with optionally a range datetime that returns the amount of time total and a list of leases with their respective totals.

**Comment by Redm4x** [comment]
The new endpoint is live: https://api.cloudmos.io/internal/leases-duration/akash1qh0f0h7jlq4x5gpxghrxvps5l09y7uuvcumcyd
There is documentation on the [Pull Request](https://github.com/akash-network/cloudmos/pull/124).
