### ISSUE TITLE
Implement API endpoint for new GPU pricing

### ISSUE THREAD

**Issue by baktun14** [akash-network/console#121]
### List of GPUs endpoint

**Output**
- List of models with each a list of ram and each a list of interfaces with each a min,max,avg

### Single GPU endpoint

**Input:**
- model
- ram
- interface

**Output:**
- Min, Max, Avg

![image](https://github.com/akash-network/cloudmos/assets/15185355/e0e7080b-263a-475a-aa6d-e455c22ba591)

We need to find a proper way to query the actual pricing of the gpu models available on the network. We could have a script that deploys a workload for each of the models and see the bids that it returns.

**Comment by baktun14** [comment]
Ref: https://github.com/akash-network/website-revamp/issues/51

**Comment by Redm4x** [comment]
March 26, 2024: 

Current preview url: https://api-preview.cloudmos.io/internal/gpu-prices

I'll deploy an updated version to production with improved pricing accuracy this afternoon.
I created a bot that will create deployment daily for every gpu model. This will help make sure we have up to date pricing for every model.

Until gpu ram and interface is included in bid attributes it will be hard to get accurate pricing per ram/interface. Currently the same pricing is shared between every version of the same model.

**Comment by Redm4x** [comment]
The api is live. Once there is a feature to get pricing directly from providers we can refactor it to get it's pricing from there instead.

#142
