### ISSUE TITLE
Implement logger

### ISSUE THREAD

**Issue by ygrishajev** [akash-network/console#140]
Currently project utilises nodejs `console.log` for logging with doesn't provide a desired observability or debugging experience.  Some of the issues:
1) noisy tests outputs
2) no way to filter or identify logs by levels which complicates decision making
3) logs are simple strings which would complicate indexing if stored in tools like kibana or grafana

A good way to address this would be having a proper logger having common features. One of the good ones is [pino](https://github.com/pinojs/pino).

- [ ] replace all the logs in the backend services with a properly scoped pino logger

**Comment by anilmurty** [comment]
+ consider adding a way to preserve and review logs after the deployment is closed

**Comment by ygrishajev** [comment]
@anilmurty this task is more about app level logs for cloudmos services. Infrastructure for managing logs is a different story. Clients' deployments logs is even more further topic.

**Comment by hiroyukikumazawa** [comment]
I will do this, assign me plz.

**Comment by ygrishajev** [comment]
This one is resolved for the api already. Now we need to put that logger into a package and reuse in other apps.
