### ISSUE TITLE
Storage class ram

### ISSUE THREAD

**Issue by baktun14** [akash-network/console#147]
TODO
- [ ] SDL Builder: Add the `ram` class to list of possible storage classes.
- [x] Akashjs: Add `persistent: false` to the storage class by default if it's not set (in the case of class: ram)

**Comment by Redm4x** [comment]
April 9, 2024:

A PR for akashjs will be going today, we'll update Cloudmos & Console with it soon after. As for the SDL builder, it's probably best to wait for the rebrand to be done before changing the UI. In the mean time users can still use ram storage by editing the SDL.

**Comment by brewsterdrinkwater** [comment]
April 16th, 2024

- PR will be made for this soon.

**Comment by Redm4x** [comment]
RAM storage is now supported in the sdl, will close this task and create a new one for tracking the SDL builder support

#175
