### ISSUE TITLE
(FEATURE REQUEST) Add Copy/Paste into SHELL

### ISSUE THREAD

**Issue by blevlabs** [akash-network/console#150]
Adding copy/paste into the SHELL would be incredibly useful.

**Comment by ghost** [comment]
Clarification: Web Shell

**Comment by anilmurty** [comment]
Console really can't enable this if the container image does not have support for Shell in the container image. I'll close this unless I'm missing something. The best we can do is put some documentation or a tooltip around it.

**Comment by baktun14** [comment]
Added a note to add a tooltip to further explain why copy/paste might not work for some containers.
