### ISSUE TITLE
Upgrade typescript to the latest version 5

### ISSUE THREAD

**Issue by ygrishajev** [akash-network/console#153]
The project is currently using an older version of TypeScript. Upgrading to TypeScript version 5 will bring several benefits like:

1. **Latest Features**: TypeScript 5 comes with new features that are not available in the current version we are using. These features can help us write more efficient and cleaner code.  
2. **Improved Performance**: The newer version of TypeScript has improved performance in terms of both compilation and code execution. This can lead to faster development cycles and a better user experience.  
3. **Long-Term Support**: By upgrading to the latest version, we ensure that we are using a version that is actively maintained and supported. This can help us avoid potential issues and bugs that might exist in older versions.  
4. **Keeping Up with the Ecosystem**: Many popular libraries and frameworks are starting to require newer versions of TypeScript. To ensure compatibility and take advantage of these tools, it's important to keep our TypeScript version up to date.

- [ ] Upgrade api
- [ ] Upgrade deploy-web
- [ ] Upgrade indexer
- [ ] Upgrade landing
- [ ] Upgrade provider-proxy
- [ ] Upgrade shared

**Comment by baktun14** [comment]
![image](https://github.com/akash-network/cloudmos/assets/15185355/e90c8760-eb27-4d98-a17e-bf66433a334b)
This should be straightforward and easy to do.
