### ISSUE TITLE
[Feature Request] Reminder/Warning Notification Service for Cloudmos Deployment Remaining Funds Availability. 

### ISSUE THREAD

**Issue by dominikusbrian** [akash-network/console#166]
**Background**
In Cloudmos deployments, active deployment onto Akash network would require user to add a minimum 0.5 AKT as the outstanding BALANCE of the given deployment. Depending on the COST of the deployment, the dashboard will calculate and show and approximate TIME LEFT variable that specify a safe estimate of duration in which the deployment won't be abruptly stopped due to insuffient balance. 
Currently when this variable TIME LEFT goes under 7 days, There will be a red-colored ! warning sign shown. But often when user have many ongoing deployments it is getting not easy to track them all without checking manually. 

**Feature Requested**  
Following on the discussions that happened [here](https://discord.com/channels/747885925232672829/1111748832489910332/1231862590049751131)  Seems that it would be useful for user to be able setting up a Reminder/Warning Notification service they can Opt-In , in case they want a more swiftly and time efficient manner of knowing which of their ongoing deployment requires more funds. 

**Benefit**
At this moment, one way to avoid having insufficient fund is to lock more funds so to have a balance that is sufficient for long period of time. For lightweight deployment this is often not a big deal. But when it comes to deployments that may cost hundreds of $ per month, this will be a bit inconvenient to have liquidity stuck in a deployment (without the benefit of staking APY and such.)

**Implementation Idea**
The implementation of this feature supposed to be pretty straightforward. Since each user that have deployment suppose to already register their email address. The Notification Service simply need to check on the TIME LEFT variable and send a reminder message to user when it is lower than a certain number(s), to be specied by default, or self-defined by user when opting in. The scan period for this variable can be of Daily interval or every 3-Days interval and that should have suffice. The email sending can simply use the info@cloudmos.io email backend that already in place. 

![image](https://github.com/akash-network/cloudmos/assets/60097047/6be0509f-1ac6-471f-a6dd-f777b8f8b7ec)

**Comment by anilmurty** [comment]
Thanks @dominikusbrian - we definitely have plans to implement notifications.

**Comment by baktun14** [comment]
https://github.com/akash-network/console/issues/498
