### ISSUE TITLE
Cert disappears, all config data is lost

### ISSUE THREAD

**Issue by martinwhitman** [akash-network/console#186]
I haven't consciously cleared my browser data or deleted anything that would be in localStorage in Chromium, but my cert disappeared and now all my config data is gone, including all my SDLs going back a long time. Would there be some way of storing the cert offline, or not in a way that is cleared by the browser?

**Comment by anilmurty** [comment]
seems related to https://github.com/akash-network/cloudmos/issues/56

@martinwhitman - just to confirm - you didn't switch between console and cloudmos while you were testing this, correct?

**Comment by anilmurty** [comment]
@martinwhitman - we have discussed two potential solutions to this (as document in #56 ) - we're curious, if you had option 1 (to backup and restore) would you use that?

**Comment by martinwhitman** [comment]
Yes, that is correct, I did not switch from console to cloudmos.

And Yes, a backup and restore would be great.
________________________________

**Comment by baktun14** [comment]
An export/import of local storage has been implemented in #204. We'll continue to improve this in the future.
