### ISSUE TITLE
conversion issue in maximum amount

### ISSUE THREAD

**Issue by tennox** [akash-network/console#187]
![IMG_20240508_193526_307](https://github.com/akash-network/cloudmos/assets/2084639/87b4d713-f55f-4f23-bd85-016b878d1093)

... at least I hope it's a conversion issue - otherwise I'd wouldn't be a safeguard appropriate for my wallet 😋

**Comment by baktun14** [comment]
The pricing is in `uAKT` which is the lowest unit for AKT equal to 0.000001, so this is why it equals to a ridiculously big number extrapolated to a monthly payment.

**Comment by tennox** [comment]
Just to make sure we are understanding each other...
Are you seeing the dollar sign in front of the 1,8 billion? 😅

**Comment by baktun14** [comment]
Yes, this settings just says: "I want see bids from providers that will cost less than 1.8B$" as written in the tooltip
