### ISSUE TITLE
Improve Monorepo Management and Dependency Handling

### ISSUE THREAD

**Issue by ygrishajev** [akash-network/console#209]
### Current Problem

Our current project structure and dependency management are causing several issues:

1. **Inconsistent Directory Structure**:
   - Different apps and packages are not well-separated, leading to confusion and potential conflicts.

2. **Dependency Duplication**:
   - Dependencies are not shared efficiently across apps and packages, resulting in duplication and increased maintenance overhead.

3. **Lack of Unified Configuration**:
   - There is no centralized configuration for tools like TypeScript, Jest, Prettier, and ESLint, causing inconsistencies and redundant configurations across the project.

4. **Build and Deployment Challenges**:
   - The current setup complicates CI/CD processes and deployments due to inconsistent and scattered configurations.

### Proposed Solution

This issue aims to address the above problems by:

**Adopting npm Workspaces**:
   - Implement a monorepo approach using npm workspaces to ensure a consistent directory structure, separating packages and apps.

### Benefits

- **Consistent directory structure** for better project organization.
- **Efficient dependency sharing and deduplication**, reducing maintenance overhead.

### This would open a clear path to:
- **Centralized tool configurations** for consistency and reduced redundancy.
- **Streamlined CI/CD processes and deployments** with a unified approach.

**Comment by baktun14** [comment]
I think we can close this one? @ygrishajev
