### ISSUE TITLE
Centralize ESLint and Prettier Configurations in Monorepo

### ISSUE THREAD

**Issue by ygrishajev** [akash-network/console#223]
Currently, our monorepo contains multiple apps and packages, each with their own ESLint and Prettier configurations. This has led to inconsistencies across our codebase, as some configurations differ from others, and some apps/packages do not have configurations at all.

To simplify maintenance and ensure consistent code style across all projects, we propose to centralize these configurations at the root of the monorepo. This means we will have a single ESLint configuration and a single Prettier configuration that all projects in the monorepo will adhere to.

### Goals

- Remove individual ESLint and Prettier configurations from each app/package.
- Create a single ESLint configuration and a single Prettier configuration at the root of the monorepo.
- Ensure all projects in the monorepo use these centralized configurations.

### Benefits

- Simplifies maintenance: With only one set of configurations to maintain, it will be easier to make updates and ensure consistency.
- Ensures consistency: All projects will follow the same code style guidelines, making the codebase easier to read and understand.
- Streamlines new projects: Any new projects added to the monorepo will automatically use the centralized configurations, reducing setup time.

We believe this change will greatly improve our code quality and developer experience. We welcome any thoughts or suggestions.

**Comment by baktun14** [comment]
I think we can close this one?
