### ISSUE TITLE
[Console 2.0] CI/ CD style deployments through Console

### ISSUE THREAD

**Issue by anilmurty** [akash-network/console#226]
## Summary
This issue tracks the work to implement the prototype presented by the @hoomanhq team in https://github.com/orgs/akash-network/discussions/562 & https://github.com/orgs/akash-network/discussions/522, into Console. This will allow people to be able to connect a github repo, having it automatically build and redeploy and essentially have a vercel like experience with Akash/ Console.

### Suggested Design

- Remove "Hello World" Tile and add tile called "Build & Deploy". Description text "Build & deploy your own React/ Node app from code located in Github"
- Clicking it has options to specify the following things (note that for private repositories, GH OAuth via GH app will be implemented, with user actions via the UI)
   - Github Repo location
   - Branch (default "Master")
   - Private Repo checkbox which will ask for creds, if checked
      - Username
      - Password
   - NodeJS version: Text box or Dropdown
   - SSH Public Key: Text Box
   - Generate SSH key (will generate pub + private key pair, populate pub key and promp user to download and save private key)
   - SSH instructions

For a Private Repo: there are additional steps to authorize installation of the Github App - we ideally want to do some Akash branding around this
   
![Screenshot 2024-06-04 at 2 40 53 PM](https://github.com/akash-network/cloudmos/assets/19495789/c23b6c3f-27a6-4ec1-ab74-220a1631adcf)
When the deployment is done - is it possible to point back to the repo that this is linked to, in the lease details page?

**Comment by anilmurty** [comment]
@hoomanhq - per our discussion, I'm going to assign this to you

**Comment by hiroyukikumazawa** [comment]
I want to participate to this task too.

**Comment by anilmurty** [comment]
hey @hiroyukikumazawa - this feature will be implemented by @hoomandigital and team as part of https://github.com/orgs/akash-network/discussions/606 -- that said, if you are interested in regular contributions, I'll tag you on some that we may be interested in bulding going forward + I'd encourage you to come to sig-clients (cc @brewsterdrinkwater - can add you to the meeting invite)

**Comment by HoomanDgtl** [comment]
We are progressing well on this initiative and are currently testing the work internally. The development is nearly complete, and we plan to merge it into the main site within the next two weeks. Thank you.
