### ISSUE TITLE
[Console 2.0] Cloud-VM style deployments via Console

### ISSUE THREAD

**Issue by anilmurty** [akash-network/console#227]
### Overview and Problem Statement
One of the most commonly requested things from customers/ partners/ users is a similar experience to public clouds where a user is able to request a VM running on a specific (pre-set) hardware configuration, along with a plain OS image (typically linux) that they can just SSH into and work with (install any packages like git, python, pytorch, huggingface models etc). When they come to akash, they expect a similar experience.

### Suggested Design
- [ ] Merge the "Upload SDL" tile into the "Build your template" tile by making in a button next to the "Builder | YAML" options -- something like below (but use the common component for the button and font)

![Image](https://github.com/akash-network/cloudmos/assets/19495789/70a6ef88-472d-465d-8adf-c4eaa951dc36)

- [ ] Add a new template in the main Deploy page called "Plain Linux" with description "Choose from multiple linux distros. Deploy and SSH into it. Install and run what you want after that."

![Image](https://github.com/akash-network/cloudmos/assets/19495789/10363fb5-8d96-4b4d-9cab-051d6960b49a)

- [ ] Clicking into it lets the user specify the following:
    - Linux Distro: Dropdown selector with options to choose:
       - Ubuntu
       - CentOS
       - Debian
       - Suse
    - Public SSH key: Text box for user to paste in their public SSH key
    - Generate: button to click that will generate a pub/ private SSH key combo and populate the pub key text box with the generated pub key.
    - Remove the "service count" config option (more than 1 does not make sense for SSH into a linux image
    - Rest of the SDL builder options (preset to what's needed for the linux image) + persistent storage 
  
- [ ] Add documentation to tell the user how to SSH into the container once it is running. Ideally we should show this in the lease details page

**Comment by hiroyukikumazawa** [comment]
I will develope this.

**Comment by anilmurty** [comment]
Hey @ygrishajev - when you are ready to work on this please reach out to @andy108369 to coordinate docker images and embedding the user SSH pub key (with sshd install)

**Comment by anilmurty** [comment]
Added suggested design changes for now. We will do a full refresh of this page at a later point (with inputs from @aktdenis ) but this is for us to get the functionality in place, for now.

**Comment by anilmurty** [comment]
hey @hiroyukikumazawa - thanks for the interest here. Sorry for missing your comment earlier. This one is on the core team's plate but happy to discuss other potential things you could contribute to (cc @baktun14 )

**Comment by hiroyukikumazawa** [comment]
> hey @hiroyukikumazawa - thanks for the interest here. Sorry for missing your comment earlier. This one is on the core team's plate but happy to discuss other potential things you could contribute to (cc @baktun14 )

So I don't have access for this issue, right?

**Comment by anilmurty** [comment]
@hiroyukikumazawa - correct, this is assigned to @ygrishajev for now. Are you set up to be able to build and run console locally? We should discuss this further - are you on our discord server? If so, what's your handle?

**Comment by hiroyukikumazawa** [comment]
> @hiroyukikumazawa - correct, this is assigned to @ygrishajev for now. Are you set up to be able to build and run console locally? We should discuss this further - are you on our discord server? If so, what's your handle?

Not fully, just run the frontend
@terratinker
And this is my discord id.

**Comment by anilmurty** [comment]
@hiroyukikumazawa - are you interested in working on the first sub task under this issue? 
"Merge the "Upload SDL" tile into the "Build your template" tile by making in a button next to the "Builder | YAML" options -- something like below (but use the common component for the button and font)"
If you are unable to get to this in the next 2 days, then the core team ( @ygrishajev ) will implement it

**Comment by hiroyukikumazawa** [comment]
I will do this

**Comment by hiroyukikumazawa** [comment]
Please check the pr https://github.com/akash-network/cloudmos/pull/244
