### ISSUE TITLE
Improve open source core contributors onboarding

### ISSUE THREAD

**Issue by baktun14** [akash-network/console#229]
### **Overview and problem statement**

We’re adding more contributors to the Console product suite and we need to better structure the repo to be able to properly onboard and scale the contributions with less friction. On top of that, we’re introducing new applications (Praetor/Provider) into Console and we want to share frontend components.

- Improve readmes
  - The main readme should be focused on activation as quickly as possible
  - Move the architecture and design to other readmes
- The repo has been refactored into workspaces and the readmes need to reflect that
- Fix docs based on workspaces
- Env variables
  - Add .env.example
  - Add more docs about the values to set
- Conventions
- Implement turborepo to launch console in a single command

**Comment by hiroyukikumazawa** [comment]
@baktun14 
Could you explain this in more detail?

**Comment by schnetzlerjoe** [comment]
@ygrishajev @baktun14 What is the best way to launch Console locally? Trying to work on https://github.com/orgs/akash-network/projects/5/views/1?pane=issue&itemId=48011058 ?

**Comment by baktun14** [comment]
Hey @schnetzlerjoe, @Redm4x tried to test and had some issues mentionned here https://github.com/akash-network/cloudmos/issues/62#issuecomment-2161130346

You should be able to follow the instruction here https://github.com/akash-network/cloudmos?tab=readme-ov-file#running-the-application
