### ISSUE TITLE
Shared packages

### ISSUE THREAD

**Issue by baktun14** [akash-network/console#230]
Praetor brand will be dissolved into Console to unify the Akash experience and we want to share the same styling with Console by creating a library of components (tailwind/shadcn)

- [x] Create the shared component library under a folder called “ui” in the packages folder
- [x] #250
- [x] Refactor deploy-web to use the config and components
- [x] Add documentation to import components
- [x] Extract re-used custom components from stats + console
- [x] Fix the form components
- ~Add storybook to be able to view and develop shared components~

**Comment by dominikusbrian** [comment]
Will there be opportunity to contribute to this effort as open-source developer ? Contributing to this would be helpful in understading and gaining more experience for building a frontend for projects that are integrating with Akash network.

**Comment by anilmurty** [comment]
@dominikusbrian - yes - the cloudmos/ console code is open source and so is the praetor code

**Comment by baktun14** [comment]
Update June 18 2024:
- Extracted all the shadcn components from deploy-web and stats-web into packages/ui and replaced everywhere we use them.
- I will continue to extract more custom re-used components in another branch

**Comment by baktun14** [comment]
Update June 25 2024:

- Currently working in another branch to extract more shared components

**Comment by baktun14** [comment]
Update July 2nd 2024:
- Extracted more custom components #256 
- I will continue working on this, mainly the form components for the provider console and deploy console

**Comment by baktun14** [comment]
Update:

- Currently working on refactoring the form components

**Comment by baktun14** [comment]
Update:

- I had issues with the schema library for form validation, but figured it out this morning. I will create my pr this week to finish this task and set the standard for form schema validation and components.

**Comment by baktun14** [comment]
Update:
- I figured out all the edge cases for using zod as a schema validation for forms and created my pr https://github.com/akash-network/console/pull/283
- This pr sets the standard for form validation in all the clients
- I will close this issue once this pr is merged.
