### ISSUE TITLE
Authz CLI

### ISSUE THREAD

**Issue by baktun14** [akash-network/console#235]
- Create a cli to authz new wallets for fees and deployments.
- The purpose of this cli is to give new users free trials

**Comment by Redm4x** [comment]
Ended up doing tiny script just to generate the wallets this one time. There is no authz automation. If we want to generate more wallets in the future, we could add authz automation to the script to automatically configure Deployment Grants & Fee Grants and make it more user-friendly, but for now I'm closing this as it is not planned.
