### ISSUE TITLE
[Console 2.0] Fiat Payments

### ISSUE THREAD

**Issue by baktun14** [akash-network/console#247]
### **Overview and Problem Statement**

One of the most, if not the most, requested feature of the Akash Console is to be able to pay with fiat, aka credit cards. The system will be credit based (pre-payment), which will easily allow for free trial through free credits, like all the other cloud platforms currently do.

The goal is to keep the current deployment UX the same and only abstract the wallet interactions with a managed wallet server side.

This is a high level specification of the order and how we will implement the system.

- [x] API to interact with the managed wallet
  - [x] Class to manage wallets (Create wallet derived from main seed, Authz from main wallet to user wallet, sign transactions)
  - ~~[ ] Class to manage deployments (send manifest to provider, interact with provider for logs/shell, write tests, need to think about network upgrades)~~
  - [x] Generic signing tx endpoint, instead of creating specific endpoints for each of the transactions from the frontend
  - [x] User service to assign wallet/deployments (Update the db schema, write tests)
  - [x] Structure the payment API module/router
- [x] Credit manager; scheduled tasks to manage user credits
  - ~~[ ] Auto-refill deployment deposits~~
  - [x] Auto-refill authz for the user managed wallets
  - [x] Implement Stripe integration
  - ~~[ ] Auto-refill account credits with credit card~~
  - [x] Improve logging
  - [x] Free trial
- [x] Frontend
  - [x] Deployment detail, and everywhere we display the balance, modify to hide balance of the deployment since it's handled for the user
- [ ] Sign in with Github
- [ ] Email notifications
  - [ ] Credit purchase confirmation
- [ ] Billing section
  - [ ] Credit transaction history

### **Db Schema changes**

**v1.0**

- user_payment
  - user_id? null when anonymous
  - AddressIndex (hdpath)
  - Address
  - StripeCustomerId
  - CreditAmount

- user_certificate
  - cert
  - cert_key (Encrypted)
 
- UserDeployment
  - Name
  - Dseq
  - SDL (Encrypted)

- CreditActivity (For integrity and debug + billing)
  - Add/Remove credit
  - Authz Tx hash
  - StripePaymentId

**Comment by ygrishajev** [comment]
At the moment, initial wallet creation is implemented on the backend, allowing for the creation of a wallet for a user and granting it a defined trial spending limit. The next steps involve using that wallet to create deployments. The following steps are currently in progress:
	1.	A generic sign endpoint is being added so we can sign transactions from the console UI as usual but on our backend (~1-2 days).
	2.	Updates to the console UI to use that endpoint (~1 week).

With the above, we should be able to adjust the UI to allow users to choose fiat payments, receive a wallet with trial allowance, and create deployments.

Upcoming tasks:
	1.	Billing setup in the UI (~1 week).
	2.	Implementing fiat billing endpoints on the backend (likely webhooks) (~1 week).
	3.	Regular jobs to refill wallets and charge users (~2-4 days).
	4.	Critical notifications (~2-4 days).

Note: all the estimates are approximate as I personally see them.

**Comment by ygrishajev** [comment]
spinned up a staging env with the current progress https://beta.cloudmos.io/

**Comment by baktun14** [comment]
I will close this issue as completed and create separate issues for the other features.

**Comment by alexx855** [comment]
Mind if i suggest to use stripe elements instead of redirecting the user to stripe? Stripe does also support payments with crypto now, maybe the UI can be simplified and we can just allow user to top up crypto using stripe, without leaving the console or switching modes

**Comment by ygrishajev** [comment]
hey @alexx855 thanks for the suggestion. This can make sense for sure. The current implementation is an first easiest MVP, so we're going to be improving this with time. This kind of feedback is helpful.

@anilmurty FYI
