### ISSUE TITLE
Console shows a deployment as active, but provider says it is closed

### ISSUE THREAD

**Issue by vpavlin** [akash-network/console#294]
I have an old deployment which I attempted to update, but after update it never deployed (DSEQ 16605857)

The console shows it as `active` though
![Screenshot from 2024-08-08 17-11-52](https://github.com/user-attachments/assets/ba34853a-945d-4bb0-a043-ce0c67929b63)

The provider (Europlots) confirmed the deployment is not active on their cluster and is probably closed. The browser console also shows following errors

```
POST ￼https://providerproxy.cloudmos.io/ 500 (Internal Server Error)
{message: 'Request failed with status code 500', name: 'AxiosError', code: 'ERR_BAD_RESPONSE', config: {…}, request: XMLHttpRequest, …}
```

**Comment by baktun14** [comment]
Hey, there was an incident with the Europlots provider on Friday. I believe this is a side effect of what happened. The leases got closed on the provider, but perhaps it took a bit more time to update the status on chain.
