### ISSUE TITLE
Improve stats app charts

### ISSUE THREAD

**Issue by baktun14** [akash-network/console#298]
It's currently only possible to zoom for a specific period of time for all the charts on stats.akash.network. We would need to change chart library to another one to support this type of custom zooming.

Suggestions:
https://www.tradingview.com/lightweight-charts/

**Comment by forbesus** [comment]
Hello @baktun14 I will handle this task

**Comment by ShinySyntax** [comment]
Hello, @baktun14 
May i take this issue?

**Comment by baktun14** [comment]
Hey @forbesus and @ShinySyntax , thanks again for your interesting in contributing. @forbesus I will assign this to you if you're willing to give this issue a shot.

**Comment by forbesus** [comment]
Okay, I can do this @baktun14
