### ISSUE TITLE
Feat: Add Stats APIs for per provider stats (for Provider Console)

### ISSUE THREAD

**Issue by anilmurty** [akash-network/console#307]
### Problem Statement
For the work happening in #220 - one of the things we would like to do is offer a per provider dashboard. For the first iteration of the provider console dashboard, we intend to keep it simple and offer a subset of what is available in https://stats.akash.network/ but filtered to the specific provider.

### Requirement

Offer APIs to query the following stats per provider - ideally available for 7d, 1m or ALL time (similar to stats page):

Network Summary Stats
- [ ] USD Spent (24h)
- [ ] Total USD Spent
- [ ] New Leases (24h)
- [ ] Total Leases

Resources Leased Stats
- [ ] Active Leases
- [ ] Compute
- [ ] Graphics
- [ ] Memory
- [ ] Storage

Spent Assets Stats
- [ ] AKT Spent (24h)
- [ ] Total AKT Spent
- [ ] USDC Spent (24h)
- [ ] Total Spent USDC

Note that this is just using the labels for the stats as they appear on the stats page. The labels we will use in the UI will be different (for example "AKT Earned")

**Comment by anilmurty** [comment]
@jigar-arc10 - please add anything I missed

**Comment by Redm4x** [comment]
September 17th, 2024

The first iteration of this is almost done and should be available this week. It will include all the listed stats for the current day. Providing historical data (7d, 1m, all) will be a bit more challenging and will come as a second iteration later on as it will probably require changes to the indexer.

**Comment by Redm4x** [comment]
Closing this as the basic dashboard endpoint is done & merged. The remaining graph endpoint has a lower priority and will be tracked in #473
