### ISSUE TITLE
Ensure all env vars are in SCREAMING_CASE

### ISSUE THREAD

**Issue by ygrishajev** [akash-network/console#310]
Some vars in the project are in camelCase which could cause issues in some environments and is not common. We need to rename to SCREAMING_CASE and make sure it doesn't break the apps.

**Comment by anilmurty** [comment]
@hiroyukikumazawa - interested in taking this one? (cc @brewsterdrinkwater to figure out bounty)

**Comment by hiroyukikumazawa** [comment]
ok, interested @anilmurty
