### ISSUE TITLE
change default $uAKT in rent GPU and plain linux forms

### ISSUE THREAD

**Issue by anilmurty** [akash-network/console#320]
Increase both (rent gpu page and plain linux page) defaults to 10000 $uAKT

![Screenshot 2024-08-19 at 3 24 42 PM](https://github.com/user-attachments/assets/1965f679-ad6d-48a5-a2a6-5c500c6f18e4)

**Comment by anilmurty** [comment]
I guess it is this?  https://github.com/akash-network/console/blob/fd92d157884eab79e6dea7c248957fa1d61a58b3/apps/deploy-web/src/utils/sdl/data.ts#L147

**Comment by baktun14** [comment]
@anilmurty Should I create a pr on awesome akash to change the default value to 10000 for all the templates?

**Comment by baktun14** [comment]
https://github.com/akash-network/awesome-akash/pull/562

**Comment by anilmurty** [comment]
awesome - thanks @baktun14

**Comment by baktun14** [comment]
#324
