### ISSUE TITLE
Improve stats app resiliency

### ISSUE THREAD

**Issue by Redm4x** [akash-network/console#330]
# Improve stats app resiliency

## Problem

Most of the [stats app](https://stats.akash.network/) data come from the `/v1/dashboard-data` endpoint. This endpoint poorly handle exceptions so if any error occurs, the entire dashboard breaks. In this specific case, only the "Bonded token" loading failed, but all the tiles are missing.

![image](https://github.com/user-attachments/assets/8b426e17-5143-4f42-9ad3-3ff7927cc614)

## Proposed solution

We need to make sure that the endpoint is resilient and won't break if some of the data loading fail:
- [ ] In the `/v1/dashboard-data` endpoint. Make sure that if anything fail to load, the rest is still returned
- [ ] In the `getChainStats` function. Make sure that if a query fail, the others are still returned
- [ ] In the stats app. Make sure that if a row or tile data is missing from the api response, the others are still rendered

**Comment by forbesus** [comment]
Hello @Redm4x I can handle this task

**Comment by baktun14** [comment]
Hey @forbesus are you still up for this task?

**Comment by forbesus** [comment]
Sure @baktun14

**Comment by forbesus** [comment]
Hello @baktun14 Will you assign this task to me?

**Comment by baktun14** [comment]
@forbesus Do you need help with something?

**Comment by forbesus** [comment]
Can we chat via discord for smoothly communication? @baktun14 

My discord name in community is `analos.xyz`

**Comment by baktun14** [comment]
@forbesus Ok I'll add you
