### ISSUE TITLE
Improved managed wallets error handling

### ISSUE THREAD

**Issue by baktun14** [akash-network/console#340]
- The errors happening in the api return a generic 500, but we should handle return better error messages based on known potential errors.
- Example: When user is out of credits
![image](https://github.com/user-attachments/assets/ebc9df09-746d-4e9a-8577-582982c5142b)
![image](https://github.com/user-attachments/assets/0afcc502-f363-4c5b-921a-93c30f425e8a)

**Comment by ShinySyntax** [comment]
Hello, @baktun14 
I am interested in this issue.
could you give me this issue?

**Comment by baktun14** [comment]
Hey @ShinySyntax this is being handled by @ygrishajev , but thanks for you interest.
