### ISSUE TITLE
Authz grants balance

### ISSUE THREAD

**Issue by baktun14** [akash-network/console#354]
- Properly show authz balance for managed and un-managed wallets
- Display the total balance including authz deployments for managed wallets

**Comment by Oyase-shinobi** [comment]
Hello @baktun14 
I will fix this issue
may I take this issue?

**Comment by baktun14** [comment]
@Oyase-shinobi Thanks, but I already started it.

**Comment by Oyase-shinobi** [comment]
@baktun14 
I see
Thank you for your contacting

**Comment by baktun14** [comment]
#359
