### ISSUE TITLE
Feature request: display deployment restart count

### ISSUE THREAD

**Issue by ghost** [akash-network/console#367]
I think this could be a good feature addition to the Console's Deployments tab https://console.akash.network/deployments where users could see the amount of their pod restarts (probably also different colors green-yellow-orange-red depending on avg restart count a day or so).

When deployment has a memory leak, low memory set or any other issue, it will keep restarting.

**Comment by hiroyukikumazawa** [comment]
Good point!

**Comment by baktun14** [comment]
@andy108369 is it possible to know how many times a pod has restarted?

**Comment by ghost** [comment]
> @andy108369 is it possible to know how many times a pod has restarted?

lease-events doesn't give this info? if not, then it should be a feature request to the provider GH repo

**Comment by baktun14** [comment]
> > @andy108369 is it possible to know how many times a pod has restarted?
> 
> lease-events doesn't give this info? if not, then it should be a feature request to the provider GH repo

Ah perhaps, but in any case, the lease events drop off after some time so it's not reliable. I create an issue over the weekend for that specifically. https://github.com/akash-network/support/issues/252

**Comment by ghost** [comment]
> > > @andy108369 is it possible to know how many times a pod has restarted?
> > 
> > 
> > lease-events doesn't give this info? if not, then it should be a feature request to the provider GH repo
> 
> Ah perhaps, but in any case, the lease events drop off after some time so it's not reliable. I create an issue over the weekend for that specifically. [akash-network/support#252](https://github.com/akash-network/support/issues/252)

I think it only keeps recent lease-events per pod which then disappear after short time.
So I guess it should be a feature request anyway for the provider to report the pod restart count.
And yeah, just remembered that I've already had a ticket for this one opened last month => https://github.com/akash-network/support/issues/246
