### ISSUE TITLE
Console should not discard manifest when user closes deployment on the Choose Provider screen

### ISSUE THREAD

**Issue by vpavlin** [akash-network/console#375]
When I create a deployment which does not get any bids (e.g. combination of persistent storage, IP and GPU does nto match any provider) and I close it from the "Choose Provider" screen, the Console goes to `Deployments` screen and my deployment manifest is lost.

It would be great if we could go back to `Create Deployment` to tweak it and submit it again

**Comment by baktun14** [comment]
We do store the manifest in your browser when you create a deployment, so you can actually "redeploy" when you close your deplyoment. Simply uncheck the active checkbox and you'll see your deployment that you can edit and redeploy. 
![image](https://github.com/user-attachments/assets/39c9e066-2749-4b15-939d-51974035b4fd)
