### ISSUE TITLE
Improve GPU deployment experience

### ISSUE THREAD

**Issue by baktun14** [akash-network/console#39]
After almost 2 months since the GPU mainnet launch, we've gathered many feedbacks from the community, both from the crypto and non-crypto native users. What comes out the most is the ease of use to deploy, a "point and click solution". 

Hence, I created this topic to track the advancement on a new type of form similar to the SDL builder, but verticaly aligned for GPUs.

The form will support:
- Fully abstracted SDL
- Simplified options
- Template selection for GPU related deployments
- Easy token selection
- Easy region selection with provider attributes

**Comment by baktun14** [comment]
Once https://github.com/akash-network/support/issues/141 and https://github.com/akash-network/support/issues/124, further improvements will be enabled, making the experience of deploying GPUs better than ever!

**Comment by brewsterdrinkwater** [comment]
Oct 31st

- Wanted to have a landing page for users to deploy gpus
- Working on the SDL builder front end tool
- Ui has all of the GPU focused templates
- Separate form for now. Anil wants to think about where this will live.

**Comment by anilmurty** [comment]
Rent GPU form is complete - PR is up

**Comment by baktun14** [comment]
https://github.com/akash-network/cloudmos/pull/43
