### ISSUE TITLE
Free Trials + CC Payments - sign-in UX improvements

### ISSUE THREAD

**Issue by anilmurty** [akash-network/console#401]
Per our design discussion, we will make the following changes to limit confusing users who transition from trial to paid, from trying to start a new trial

Functionality Change:
- [x] maintain a flag (let's call it "prev_signed_in" for this issue) in browser local storage to track if the user is signed in and conditionally show or hide the trial button based on the flag (as indicated below)

1. "Home" (https://console.akash.network/) page
- [x] Remove the "your Account" pane (and the "setup billing, start trial, connect wallet " items in it) - this is to limit number of calls to action
- [x] If prev_signed_in is set show "Sign In" button and "Connect Wallet" buttons on top right (no "Start Trial" option)
- [x] If prev_signed_in is not set show "Start Trial" and "Connect Wallet" buttons 

2. Getting started with Console (https://console-beta.akash.network/get-started)
- [x] If prev_signed_in is set show "Sign In" button and "Connect Wallet" buttons (no "Start Trial" option)
- [x] If prev_signed_in is not set show "Start Trial" and "Connect Wallet" buttons 

3. Create Deployment (pop out modal for user to confirm)
- [x] If prev_signed_in is set show "Sign In" button and "Connect Wallet" buttons (no "Start Trial" option)
- [x] If prev_signed_in is not set show "Start Trial" and "Connect Wallet" buttons
- [x] if signed in or wallet connected, just deploy

5. Deployments page (https://console-beta.akash.network/deployments) 
- [x] Display message when no deployments show that says "No active deployments. If you are expecting to see some, you may need to sign-in or connect a wallet" (with sign-in and connect-wallet both being links to the actions)

**Comment by anilmurty** [comment]
@baktun14 @ygrishajev @aktdenis - I think this is what we came up with?

**Comment by Bct-crypto** [comment]
Hi @anilmurty 
I am interested in this issue.
plz let me know If I can start to work.

**Comment by anilmurty** [comment]
Hey. The core team has been working on this feature for a while so it's best if they take it. There are other issues that we can have you work on

**Comment by Bct-crypto** [comment]
Thank you for reaching out.
I 'd like to contribute to your project.
Let me know about other issues I can.
Thank you.
