### ISSUE TITLE
New "new deployment" page

### ISSUE THREAD

**Issue by anilmurty** [akash-network/console#407]
# Background
We've been working on Frictionless Free Trials, Credit Card Payments and a workflow (similar to vercel) that takes care of building a container and deployment SDL for the user. Previously we built a way for users to get a "VM-like" experience using the "container-vm" template (that let's them provide an SSH pub key and then get access to a plain linux container that they can then install what they want into).

All these features combined together make Akash network usable by non-crypto users who may not be familiar with akash or SDLs or docker containers. There is a good opportunity to revisit the new deployment page, with these features in place - so that we're meeting these non-crypto, non-akash-familar developers where they are coming from.

# Goal
The goal of this task is to redesign the new deployment page (https://console.akash.network/new-deployment) so that there are clear workflows for the 4 developer user personas we want to target:

1. For **Pure web devs** who just have a react app and don't know how or know but don't want to deal with containers or infra (and use vercel or equivalent PaaS today) => "Buid & Deploy"  (which will lead to the new "Build & Deploy" template that is under development and soon to be released https://github.com/akash-network/console/issues/226)

![Screenshot 2024-10-14 at 12 00 01 PM](https://github.com/user-attachments/assets/2c91229d-1ead-4cfb-b4c9-1f22102fcbd0)

2. For **DevOps Engineers who use EC2 or equivalent VM instances**, to deploy apps for their teams => "Container-VM" (which will lead to this existing workflow under the "Plain-Linux" template https://console.akash.network/deploy-linux?step=edit-deployment)

![Screenshot 2024-10-14 at 12 00 36 PM](https://github.com/user-attachments/assets/32dacfa7-9549-4c97-904a-851dad8f3024)

3. For **DevOps engineers who already have microservices and are already container native** with their applications => "Custom Container" which will lead to this existing workflow: https://console.akash.network/new-deployment?step=edit-deployment

![Screenshot 2024-10-14 at 12 04 22 PM](https://github.com/user-attachments/assets/e16d3318-f494-409f-a5ce-a7e2b6dcc3fb)

4. For **Akash champions (aka power users) who already have their own SDLs** and don't need help building containers or SDLs => "Upload SDL" (this will be a minimalist element on the top right of this page that Denis will add in a subsequent iteration)

# UI Design

The UI design for the new "new-deployment" page is as shown below

- Each call to action (CTA) below will lead to one of the 4 workflows above. 
- The templates are "placeholders" and will be specific AI templates (and will frequently be changed based on what's trending)
- The templates will also include logos for each

![image](https://github.com/user-attachments/assets/cb8fa3c9-5703-4bd6-bae6-13250d54f91d)

**Comment by forbesus** [comment]
Hello @anilmurty I will take this issue

**Comment by anilmurty** [comment]
hey @forbesus - thanks for the interest - let me discuss with the core team and let you know

**Comment by anilmurty** [comment]
hey @forbesus - We discussed this and realized that we need to define a better process for community code contributions. This is based on the struggles we've had with some recent PRs (larger features). We're going to work on that. Meanwhile we want to get this one out relatively quickly so we'll have the core team work on it.

**Comment by Bct-crypto** [comment]
Hi @anilmurty 
I am interested in this issue
If I can start work,  plz let me know

**Comment by anilmurty** [comment]
hey @Bct-crypto - please see my last comment. We are working on identifying good issues for community devs and also a more formal process for how they can contribute
