### ISSUE TITLE
Cloudmos Rebrand (To Akash Console)

### ISSUE THREAD

**Issue by anilmurty** [akash-network/console#41]
- [x] Use the [ShadeCN](https://ui.shadcn.com/) UI Components from Tailwind (Cloudmos currently uses Material UI)
- [ ] Update Colors and Logo to match Akash Console branding
- [ ] Break out into different products:
     - [ ] console.akash.network: Will include: Home, Deployments, Templates, SDL Builder, Providers, FAQ, Settings
     - [x] stats.akash.network: Will display Akashlytics page from deploy.cloudmos.io
     - [x] Price Compare page: will move to website (akash.network
     - [ ] Add contextual help (icons next to buttons and such)
     - [ ] Search Bar Up top: Since we won't have akashlytics in cloudmos anymore, we should either adapt this to allow searching of deployments and templates or remove it (and work on search in a separate issue)

Other Notes:
Logo branding - similar to console.akash.network
Light/ Dark mode: Cloudmos already has this so it'll be great to keep supporting it.
Templates - leave as-is for the scope of this ticket - we will work on a new design as part of https://github.com/akash-network/cloudmos/issues/42

**Comment by anilmurty** [comment]
Nov 7:

Since this is a pretty big refactor, we will also work on refactoring the API - this is getting some use from developers. This will include documenting the API in swagger.

**Comment by baktun14** [comment]
Nov 15:

Currently working on the new stats.akash.network app build with tailwind + shadcn + nextjs13

**Comment by brewsterdrinkwater** [comment]
November 22:

- Strategy is refactor gradually. Moving to tailwind in phases. 
- Going to start with Stats app (this is underway)
- Fonts need to be updated

**Comment by anilmurty** [comment]
For upcoming distributed global summit demo we will:
1. update logo and colors to Akash
2. point console.akash.network to cloudmos (with the updated logo and colors)

**Comment by brewsterdrinkwater** [comment]
November 28th, 2023

- Max has been working on the stats page. 
- UX has been updated and clean. 
- need to update the logo at the top (may remove the beta sticker)
- Still working on a few pages. 
- Want to be able to change from Sandbox, Mainnet, to Testnet.

**Comment by baktun14** [comment]
December 5, 2023:

- The rebranded app for demo purposes is done, we're working to make full encryption (https) work with docker and nextjs

**Comment by baktun14** [comment]
December 12, 2023:
- Currently working on finishing the new akash stats app
- ---
What is left to do:
- dark mode testing
- responsive
- block explorer pages
	- address
- switch between networks
- logo update
- favicon
- seo metadata
- analytics
- testing

**Comment by baktun14** [comment]
December 19, 2023:

Almost all the pages of the stats app are migrated, I will be able to release a staged version later this week.

**Comment by baktun14** [comment]
January 2nd 2024:

- All the pages are done
- Logo is updated
- Added network switch

What's left:
- Reponsive fixes and testing

I'll release on staging later this week

**Comment by baktun14** [comment]
January 9 2024:

- I created a new issue to track the Akashlytics rebrand/refactor to stats.akash.network #70

**Comment by baktun14** [comment]
Added #74 to track the removal/redirect of the rebranded stats.akash.network

**Comment by baktun14** [comment]
Added #80 to track the refactoring/rebrand of Cloudmos Deploy

**Comment by baktun14** [comment]
I think this is safe to close this issue? @anilmurty
