### ISSUE TITLE
Implement Auto Top Up UI Setting 

### ISSUE THREAD

**Issue by ygrishajev** [akash-network/console#412]
Depends on https://github.com/akash-network/console/issues/395

### Objective
Implement a new UI setting in the existing settings page that allows users to enable or disable automatic top-ups for Akash Network deployments under custodial wallets via AuthZ deployment grants.

### Scope
The task infers changes to be done to `deploy-web` Settings page. New setting should utilise existing transaction signing components.

### General Flow
1. User navigates to Setting page
2. Either on the initial tab or under Authorizations a new set of settings is added: `Automatic Top Up` for uAKT and USDC deployments.
3. Once enabled user is prompted with setting params: funds limit and expiration data.
4. Once submitted user is required to sign a relevant transaction: `/cosmos.authz.v1beta1.MsgGrant` for `/akash.deployment.v1beta3.DepositDeploymentAuthorization`.
5. The setting state should now reflect it's enabled.
6. User can disable the setting.
7. Once disabled user is required to sign relevant revoke transaction.
8. The setting state should now reflect it's desabled.

### Acceptance Criteria
- New setting is implemented.
- User should be able to enable or disable auto top ups.
- Setting state should be reflected in UI.
- Setting should utilise existing transaction signing components.
- Authorization state managed by the setting should be also reflected in the Authorizations list in Settings.
- The feature should be hidden via env var toggle.
- The feature should be covered by e2e tests.

### Design Chart For Reference
<img width="996" alt="Screenshot 2024-10-17 at 10 47 19" src="https://github.com/user-attachments/assets/dd94c94b-1dae-4ce7-8073-ac1fa1241cab">

[Link](https://app.diagrams.net/#G13u9_kJb5-ZnTi7n0JDRBFGcpUlIZD49M#%7B%22pageId%22%3A%22MBxK7MdOM9jimCUi9Otj%22%7D)

**Comment by Epic-SX** [comment]
Hello @ygrishajev 
I am interested in this issue.
 I want to handle this issue.
 Thank you

**Comment by anilmurty** [comment]
tagging @aktdenis for settings page UI to enable/ disable this feature
