### ISSUE TITLE
Extract logger into packages

### ISSUE THREAD

**Issue by ygrishajev** [akash-network/console#429]
We have a [logger](https://github.com/akash-network/console/blob/main/apps/api/src/core/services/logger/logger.service.ts) in API which provides a proper interface and functionality for the purpose. We need to be able to use it in other packages. For this it needs to be moved to a dedicated package.

Acceptance criteria:

1. a new `logging` package is created
2. the logger is moved there
3. adjustments to the constructor need to be made to ensure we can still pass the parameters which are currently imported via config
4. api is updated to depend on that package
5. should be covered with unit tests

**Comment by forbesus** [comment]
Hello @ygrishajev I will take this issue
Please assign me this issue

**Comment by ygrishajev** [comment]
hey @forbesus! thanks for your initiative. Sure, go for it!

**Comment by ygrishajev** [comment]
So, thanks to @forbesus most of this task is done.

To close it we need to add unit tests to the logger.

**Comment by forbesus** [comment]
okay, i will add unit test  @ygrishajev
