### ISSUE TITLE
Ensure logger works in all environments

### ISSUE THREAD

**Issue by ygrishajev** [akash-network/console#430]
Depends on #429

The logger as described in #429 wold only work in nodejs environment. We need to make sure it's hybrid and can work in any environment. To do so we need to adjust it to import dependencies dynamically based on environment and packages present in node_modules.

Acceptance criteria:

- logger works in both nodejs and browser env
- it dynamically loads relevant modules or uses relevant browser apis based on environment, configurations and modules present in node_modules

**Comment by forbesus** [comment]
hello @ygrishajev i checked this issue and package is working well on browser and nodejs
so i think we can integrate this in another apps

**Comment by ygrishajev** [comment]
@forbesus ok, cool. Let's start with #436 then. I think some issues might still pop up. E.g. config might not work with process env properly. We'll also need it on external packages once it is published. So this needs to be tested against built dist.

**Comment by forbesus** [comment]
hello @ygrishajev previous weekend, i checked all pino documentation again 
we are using pino-fluentd and pino-pretty modules for logging package now and fluentd and pretty all were designed for server side and working with only nodejs

i am sorry for previous confusing and didn't check about fluentd and pretty

**Comment by ygrishajev** [comment]
@forbesus No prob. Is it only fluentd? I don't think it's needed anymore. Let's just remove it
