### ISSUE TITLE
Utilise new logger in stats-web

### ISSUE THREAD

**Issue by ygrishajev** [akash-network/console#436]
Depends on #430 

See milestone for more description.

Acceptance criteria:

- logger module from packages is added to statw-web
- all console logs are replaced with properly bound logger instance calls
- redundant or not useful logs should be removed

**Comment by forbesus** [comment]
are you available to chat via discord? @ygrishajev

**Comment by ygrishajev** [comment]
@forbesus yea, same username as here - ygrishajev

However I'm not sure about my availability till mon
