### ISSUE TITLE
Audited button leads to Error page

### ISSUE THREAD

**Issue by rodri-r** [akash-network/console#45]
The providers' audited icon is clickable and it leads to an error page.  This happens on several providers that I checked and it most likely happens on every provider.

Guessing this should lead to info about the provider's auditing or maybe the icon should not be clickable until it leads correctly to provider's audited info.  

Adding screenshots
![cloudmos1](https://github.com/akash-network/cloudmos/assets/46242399/874c7d30-587a-43b3-b03f-f850a8607c9f)
![cloudmos2](https://github.com/akash-network/cloudmos/assets/46242399/1bc49e3b-ca93-48b6-a32f-db995c96536b)

**Comment by baktun14** [comment]
Hey @rodri-r thanks for reporting.

I believe I fixed it in my most recent pr #43  (not released yet.)

On released, I will test and close the issue if it's fixed!

**Comment by baktun14** [comment]
Should be fixed now.

**Comment by rodri-r** [comment]
Awesome, it works and it looks great thank you!!
