### ISSUE TITLE
Implement trial wallet expiry warning

### ISSUE THREAD

**Issue by baktun14** [akash-network/console#468]
- Show a toast when the trial starts mentionning there is 3 months left to use the credits before termination
- Show in the managed wallet the time left for the trial account
![image](https://github.com/user-attachments/assets/ca7238ae-1784-4157-abe7-a6e94a68df2f)

**Comment by baktun14** [comment]
Depends on https://github.com/akash-network/console/issues/464

**Comment by ygrishajev** [comment]
@baktun14 let's close this one due to redundancy?

**Comment by baktun14** [comment]
Sure
