### ISSUE TITLE
Cannot get API key as attached in the image.

### ISSUE THREAD

**Issue by Tony363** [akash-network/console#501]
![Screenshot from 2024-11-26 15-00-30](https://github.com/user-attachments/assets/98869389-4663-4c95-b0d3-1f09d621f9ef)

**Comment by zJuuu** [comment]
Thank you for opening this issue. This has been fixed. If you experience further issues, please feel free to open an issue in the new repository of the [akash chat api.](https://github.com/akash-network/akash-chat-api)
