### ISSUE TITLE
Refactor and improve Cloudmos API

### ISSUE THREAD

**Issue by Redm4x** [akash-network/console#54]
Refactor the Cloudmos API to enhance usability and maintainability. More and more projects in the akash ecosystem would benefit from using the cloudmos API in their project and this is the ground work for making it more accessible and developer-friendly.

- [x] Improve naming convention (consistent, lowercase, no verbs)
- [x] ~~Refactor endpoint implementations to be more consistent (controller > service)~~ Renamed providers to services for clarity
- [x] Add versioning for backward compatibility (ex: `/v1/deployments`)
- [x] Add authorization system (allow other projects to use our hosted api, enable CORS?)
- [x] Add api documentation (probably swagger)
- [x] Update cloudmos UI to call the new API
- [x] Monitoring + analytics
- [x] Add documentation to the readme

**Comment by Redm4x** [comment]
November 28, 2023: 

Started working on the api refactor and planning the new api structure (naming/versioning), Looking at the possibility to change the framework ([expressjs](https://expressjs.com)) for something more modern like [Hono](https://hono.dev/).

**Comment by Redm4x** [comment]
December 5, 2023:

[Hono](https://hono.dev/) seems like a good option. Currently implementing the OpenAPI/Swagger UI integrations.

**Comment by Redm4x** [comment]
December 12, 2023:

Going forward with Hono and their Zod/OpenAPI/Swagger intergrations. I'll share the swagger definition with the team for review as soon as it's ready.

**Comment by Redm4x** [comment]
December 19, 2023:

Still working on a prototype of the new api. Had an issue with date serializing, but it should be fixed in the latest version of Hono [edit: Confirmed Fixed].

**Comment by stayForward09** [comment]
Thanks with great API routes.

**Comment by Redm4x** [comment]
January 9, 2024:

The api versioning is implemented. Doing progress on refactoring every endpoints, I deployed a preview url for keeping track of the progress through swagger UI:
https://api-preview.cloudmos.io/v1/swagger

**Comment by Redm4x** [comment]
January 16, 2024
- Finished almost all route refactoring, only the endpoints for logged in users remain:
  - Public Api Routes :white_check_mark:
  - Private Dashboard Routes :white_check_mark:
  - Web3Index Routes :white_check_mark:
  - User Routes (login/templates/favorites) :clock1:
- Improved typescript typing across the board
- Updated the deploy-tool to use new endpoints

Expecting to create a PR this week. I updated the [Preview URL](https://api-preview.cloudmos.io/v1/swagger) with the latest changes.

**Comment by Redm4x** [comment]
January 23, 2024:

Finished refactoring the user routes (login/templates/favorites) and authorization middlewares. Created a [draft PR](https://github.com/akash-network/cloudmos/pull/86) for self review. I will add documentation to the README and make the PR ready for review today. The api key system is not implemented, but I think it's best to split it into it's own task.

**Comment by Redm4x** [comment]
January 30, 2024:

[PR](https://github.com/akash-network/cloudmos/pull/86) is in review, created issue #92 to track the remaining tasks (authentitcation system)
