### ISSUE TITLE
Add metamask support to cosmoskit 

### ISSUE THREAD

**Issue by Redm4x** [akash-network/console#62]
Add metamask support to cosmoskit using using [this code](https://github.com/akash-network/cloudmos/pull/50#issuecomment-1853247829)

**Comment by schnetzlerjoe** [comment]
This is great. Let me know if you need any help!

**Comment by brewsterdrinkwater** [comment]
Mystic Labs repo: https://github.com/mystic-lab/cloudmos/tree/metamask

**Comment by baktun14** [comment]
#216

**Comment by Redm4x** [comment]
I tried rebasing & testing the changes from #216. I could connect my metamask wallet in console, but could not create a deployment. I raised an issue in cosmoskit with the problem I faced: https://github.com/cosmology-tech/cosmos-kit/issues/470. Does it work on your side @schnetzlerjoe ?

**Comment by JohnDiBernardi** [comment]
MetaMask fully working with Akash Console:

Here's a video showing how to create a deployment: [Open Lease/Use Akash with MetaMask](https://www.loom.com/share/cbb644d9ca614bc7a0bed1772f5e2ec1?sid=33c65065-bb04-4432-937d-f339ddff6dfc)

Here's a video showing how to view your leases and notifications directly in the extension: [View Leases/Notifications in Extension](https://www.loom.com/share/ab2d233fbfc3457bbeca60217fb4951a?sid=56e614ca-23d7-48e5-9833-c8241cf2ee51)

**Comment by baktun14** [comment]
#334
