### ISSUE TITLE
Optimize Workflow for USDC based deployment

### ISSUE THREAD

**Issue by anilmurty** [akash-network/console#63]
Problem Statement: We have a lot of deployments happening on cloudmos but few that use USDC. One thing to note is that it isn't obvious in the main deployment workflow that we support USDC based deploys. This issue recommends two changes to improve that UX

- [ ] For people using the SDL builder, switching from uAKT to uUSDC does not update the SDL (not sure if this is a bug?). There also isn't an explicit "save" on that "placement" modal (should there be?).
![Screenshot 2024-02-05 at 1 15 31 PM](https://github.com/akash-network/cloudmos/assets/19495789/74a2b15f-26a6-4e41-9657-4089ba860634)

- [ ] The UI to switch from uAKT to USDC is buried one level deep. Let's surface that up to the main page so that changing it automatically sets the ibc channel to ibc/170C677610AC31DF0904FFE09CD3B5C657492170E7E52372E48756B71E56F2F1
This would be similar to the UI implemented in the "Rent GPU" page as shown below.
![Screenshot 2024-02-05 at 1 15 18 PM](https://github.com/akash-network/cloudmos/assets/19495789/71df79ed-a724-47f1-bc18-c1816cea4c73)

**Comment by ygrishajev** [comment]
> The UI to switch from uAKT to USDC is buried one level deep. Let's surface that up to the main page

Hey, I'm looking to contribute and have a question around the 2nd task: what's the main page here? SDL or root deploy page?

**Comment by anilmurty** [comment]
> > The UI to switch from uAKT to USDC is buried one level deep. Let's surface that up to the main page
> 
> Hey, I'm looking to contribute and have a question around the 2nd task: what's the main page here? SDL or root deploy page?

Thanks @ygrishajev - It needs to go on this page:
https://deploy.cloudmos.io/new-deployment?step=edit-deployment
Similar to the way it (the "Token" drop down) is on this page:
https://deploy.cloudmos.io/rent-gpu

**Comment by baktun14** [comment]
Hey @ygrishajev if you need direct assistance for something, you can reach out to me on the [Akash Discord](https://discord.akash.network). I go by Baktun14.
