### ISSUE TITLE
Create DeploymentDetails API for Praetor to use in Dashboard

### ISSUE THREAD

**Issue by jigar-arc10** [akash-network/console#65]
We need an API that takes the owner address and dseq and returns the JSON below.

```
{
    "owner": "akash18ttl3praclcd87dhsy6mczcwvnxrqltdakjn07",
    "dseq": "14228985",
    "denom": "uakt",
    "createdHeight": 14228987,
    "createdDate": "2023-12-22T16:15:09.865Z",
    "closedHeight": 14229553,
    "closedDate": "2023-12-22T17:11:31.053Z",
    "status": "closed",
    "balance": 4999783.2351,
    "transferred": 216.7649,
    "settledAt": 14229553,
    "resources": {
        "cpu": 100,
        "memory": 268435456,
        "gpu": 0,
        "ephemeralStorage": 268435456,
        "persistentStorage": 0
    },
    "leases": [
        {
            "provider": "akash1e02tys4hawc2wjexadjxztvrkxnkl9r7ym0k7v",
            "gseq": 1,
            "oseq": 1,
            "price": 0.394118,
            "createdHeight": 14229003,
            "createdDate": "2023-12-22T16:16:46.983Z",
            "closedHeight": 14229553,
            "closedDate": "2023-12-22T17:11:31.053Z",
            "status": "closed",
            "resources": {
                "cpu": 100,
                "memory": 268435456,
                "gpu": 0,
                "ephemeralStorage": 268435456,
                "persistentStorage": 0
            }
        }
    ]
}
```

**Comment by jigar-arc10** [comment]
Max B sent me API - https://api.cloudmos.io/deployment/akash18ttl3praclcd87dhsy6mczcwvnxrqltdakjn07/14228985

Which is already present in cloudmos. Can we add closedHeight to deployment and in the lease array as well?

**Comment by jigar-arc10** [comment]
Can you please add the closed date and created date in the deployment and lease in this API?

> Max B sent me API - https://api.cloudmos.io/deployment/akash18ttl3praclcd87dhsy6mczcwvnxrqltdakjn07/14228985
> 
> Which is already present in cloudmos. Can we add closedHeight to deployment and in the lease array as well?

**Comment by Redm4x** [comment]
Added the following properties on the deployment and leases: `createdHeight`, `createdDate`, `closedHeight`, `closedDate`
This change is live in the latest version of the api (`2.13.0`) @jigar-arc10
