### ISSUE TITLE
SDL Builder: mount point discarded if volume name != "data"

### ISSUE THREAD

**Issue by tennox** [akash-network/console#71]
## Reproductions
1. Go do SDL builder
2. paste yaml
3. go to builder tab

### Works:

<details><pre>
---
version: "2.0"
services:
  foo:
    image: ""
    expose:
      - port: 80
        as: 80
        to:
          - global: true
    params:
      storage:
        data:
          mount: /test
          readOnly: false
profiles:
  compute:
    foo:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 512Mi
        storage:
          - size: 1Gi
          - name: data
            size: 10Gi
            attributes:
              persistent: true
              class: beta1
  placement:
    dcloud:
      pricing:
        foo:
          denom: uakt
          amount: 1000
deployment:
  foo:
    dcloud:
      profile: foo
      count: 1
</pre></details>

Broken:
<details><pre>
---
version: "2.0"
services:
  foo:
    image: ""
    expose:
      - port: 80
        as: 80
        to:
          - global: true
    params:
      storage:
        dato:
          mount: /test
          readOnly: false
profiles:
  compute:
    foo:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 512Mi
        storage:
          - size: 1Gi
          - name: dato
            size: 10Gi
            attributes:
              persistent: true
              class: beta1
  placement:
    dcloud:
      pricing:
        foo:
          denom: uakt
          amount: 1000
deployment:
  foo:
    dcloud:
      profile: foo
      count: 1
</pre></details>

![image](https://github.com/akash-network/cloudmos/assets/2084639/e4c5c383-39df-432f-9fe4-b3c701492b21)

**Comment by baktun14** [comment]
The value of the key **must** be **data**. I think it is expected to throw an error as it will not work if you deploy with `dato` key

**Comment by baktun14** [comment]
Thanks for reporting, there was in fact a bug in the code! I will release a fix asap
