### ISSUE TITLE
Refactor Cloudmos Deploy into Akash Console

### ISSUE THREAD

**Issue by baktun14** [akash-network/console#80]
- Refactor all the components from material ui into tailwindcss + shadcn
- Refactor nextjs pages into app folder
- Rebrand the app into the Akash Console with Akash colors
- Remove Cloudmos landing page

**Comment by baktun14** [comment]
Update January 23rd 2024:

- Started refactoring Cloudmos deploy into tailwindcss/nextjs14. No issues or roadblocks.

**Comment by baktun14** [comment]
Update January 30 2024:

- Most of the layout is refactored, started working on individual pages.

**Comment by baktun14** [comment]
Update February 6 2024:

- Refactored generic reusable components
- Improved and refactored the layout
- Started working on the deployment wizard pages

**Comment by baktun14** [comment]
Update February 13 2024:

- Working on refactoring the SDL Builder and deployment creation pages
- I will fix this [issue](https://github.com/akash-network/cloudmos/issues/63) as well on the rebranded Console

**Comment by baktun14** [comment]
Update February 14 2024:
- SDL is 75% done
- Currently working on refactor form components to custom components to replace the material ui components

**Comment by brewsterdrinkwater** [comment]
February 20th, 2024

- updated a lot of items last week.
- Updated console version of Cloudmos app

**Comment by baktun14** [comment]
Update March 12 2024:
- Deployment creation is done with deployment list
- Starting deployment detail

What's left:
- Provider pages
- Settings
- Authz
- Get started
- Templates
- User profile pages
- FAQ

**Comment by baktun14** [comment]
Update March 19 2024:

- Done with deployment detail
- Started working on provider pages

**Comment by baktun14** [comment]
Update March 26 2024:

- 80% done with provider pages
- Will start working on template pages after

**Comment by baktun14** [comment]
Update April 2nd 2024:
- Provider Pages done
- Starting template page and others (Settings, Authz, Getting started)

**Comment by baktun14** [comment]
Update April 9 2024:
- Template pages are done
- Done with settings page. Authz next.
---
What's left:

- Get started
- User profile pages
- FAQ
- Fixing the styling (light/dark, mobile, etc) and few other components
- Other details

**Comment by baktun14** [comment]
Update April 16 2024:
- Finishing up the user pages, will create a PR today.
- I will finish up the last pages this week and start tackling all the details left behind during the refactor.

**Comment by baktun14** [comment]
Update April 23 2024:
- Had some issues when implementing the user pages with the nextjs app router, decided to refactor and revert back to pages router as it was before to avoid delaying the rebrand. The refactor back to pages router is done and pr will go live today.
- I will finish up the last pages this week and start tackling all the details left behind during the refactor.

**Comment by baktun14** [comment]
Update April 30th 2024:
- All the pages are done
- Fixing component and styling issues 
- Updating links to docs
- Will release to staging this week

**Comment by baktun14** [comment]
Update May 7 2024:
- All the pages are refactored
- Staging is live in testing
- Need to finish and test dark mode + responsive
- Fixing all the issues from testing and more testing

**Comment by baktun14** [comment]
Update May 14 2024:
- Fixed a lot of small details after the rebrand
- [Pr created](https://github.com/akash-network/cloudmos/pull/193) to finally merge the rebrand branch back to main
- We will release on http://console.akash.network today or tomorrow, then update Cloudmos with a banner to redirect to Console with a migrate script for the localStorage transfer
