### ISSUE TITLE
Indexer: Implement new provider discovery endpoint

### ISSUE THREAD

**Issue by baktun14** [akash-network/console#90]
- Update database schema to support multiple features for provider snapshots
- Index the new features with the provider snapshots
- Optimize the sql queries

**Comment by Redm4x** [comment]
Feb 6, 2024:

Schema is updated to track nodes and cpu/gpu models. Added support for new status endpoint. Took the opportunity for optimizing our existing sql query, the slow queries are now fixed. Will try to update the sandbox indexer by tomorrow.

**Comment by Redm4x** [comment]
Feb 13, 2024:

Mostly done in #95, will enable completly once the provider's `/version` endpoint is fixed.

**Comment by Redm4x** [comment]
Feb 20, 2024:

Created #105 for enabling grpc and some bugfixes. Will release to production this afternoon.

**Comment by Redm4x** [comment]
This was deployed for mainnet and sandbox and everything is working as expected.
