### ISSUE TITLE
GPU model display in deployment detail (Lease)

### ISSUE THREAD

**Issue by baktun14** [akash-network/console#93]
- With the indexer, we need to track the bid that was selected for the lease and extract from the bid resource the gpu model and attributes
- Implement a new api endpoint to retrieve the data
- Display the GPU model in the deployment detail

**Comment by brewsterdrinkwater** [comment]
March 12th, 2024

- This is going out this week.

**Comment by Redm4x** [comment]
This was deployed last week as planned. The gpu model is now visible in the deployment detail page.

![Image](https://github.com/akash-network/cloudmos/assets/2829180/ff1bd43e-9355-4d68-bdef-cd069061d2ae)
